dockerbox:
  build: /opt/docker-compose
  ports:
   - "80:80"
   - "2222:22"
  links:
   - couchdb:db
   - registry:registry
registry:
  image: registry:2
  ports:
   - "5000:5000"
couchdb:
  image: klaemo/couchdb
  ports:
   - "5984:5984"
